### ISSUE TITLE
Is the `SHELL=/bin/bash` in the Makefile necessary?

### ISSUE THREAD

**Issue by wucke13** [au-ts/microkit_tutorial#11]
At least on NixOS, this breaks, as there is nothing but `sh` inside `/bin`.  If bash is really needed, wouldn't `SHELL=bash` do it as well? If bash isn't needed, `/bin/sh` is required by POSXI AFAIK, so then `/bin/sh` should be used.

https://github.com/au-ts/microkit_tutorial/blob/87e791c9a55b2bf2ed5db848be6765ab906ee0be/tutorial/Makefile#L7

**Comment by Ivan-Velickovic** [comment]
I can't remember exactly why it's there. It might have been because I thought it was necessary for the `command -v` calls but I just checked and it doesn't seem like it is.

I've removed it in https://github.com/au-ts/microkit_tutorial/commit/768d53d8c0b09b676245ca3cd7f47914667c1f38.

**Comment by Ivan-Velickovic** [comment]
Thanks for reporting the issue.
