### ISSUE TITLE
signature of `uart_put_char` is wrongly specified in tutorial 

### ISSUE THREAD

**Issue by wucke13** [au-ts/microkit_tutorial#9]
The tutorial speaks of `int uart_put_char()`, but in the code it is actually `void uart_put_char(int)`

https://github.com/au-ts/microkit_tutorial/blob/e26936f959571bb0fcfb53e63e1bd2ede52fee95/website/src/part1.md?plain=1#L297C43-L297C53

**Comment by Ivan-Velickovic** [comment]
Fixed in https://github.com/au-ts/microkit_tutorial/commit/99f87e8908fdb54e3ebf650dc8c24fc6a6a28d11. Thank you!

**Comment by Ivan-Velickovic** [comment]
Whoops made a mistake, fixed in https://github.com/au-ts/microkit_tutorial/commit/e96fd454abc41f8b035b170b69be5b6cd4bf8608 as well.

**Comment by wucke13** [comment]
Sorry to bother more, but: why is it `void uart_put_char(int)` and not `void uart_put_char(char)`?

**Comment by Ivan-Velickovic** [comment]
> Sorry to bother more, but: why is it `void uart_put_char(int)` and not `void uart_put_char(char)`?

Because the hardware register for TX is 32-bits.
